version: '2'
services:

  nzedb:
    image: slydetector/simply-nzedb
    restart: unless-stopped
    ports:
      - 8800:8800
    env_file: 
      - $PWD/etc/simply_nzedb.conf
    volumes:
      - $PWD/data/covers:/var/www/nZEDb/resources/covers/
      - $PWD/data/nzb:/var/www/nZEDb/resources/nzb/
      - $PWD/data/tmp:/var/www/nZEDb/resources/tmp/unrar/
      # configuration/ is expected to contain
      #  - config.php
      #  - ircscraper_settings.php
      #  - settings.php
      #  - install.lock (only after setup has completed)
      - $PWD/data/configuration:/var/www/nZEDb/configuration/
      - $PWD/data/log/nginx-error.log:/var/log/nginx/nginx-error.log
      - $PWD/data/log/nginx-access.log:/var/log/nginx/access.log
      - $PWD/data/log/php-fpm.log:/var/log/php-fpm.log
      - $PWD/data/log/php_errors.log:/var/www/nZEDb/resources/logs/php_errors.log
      - $PWD/data/log/php_errors_web.log:/var/www/nZEDb/resources/logs/php_errors_web.log
      - $PWD/data/nginx.conf:/etc/nginx/nginx.conf
      - $PWD/data/mytop:/root/.mytop
      - $PWD/data/predb_progress.txt:/var/www/nZEDb/cli/data/predb_progress.txt
      - $PWD/data/import:/var/www/nZEDb/resources/import/
      - $PWD/data/proxychains.conf:/etc/proxychains/proxychains.conf
      - $PWD/data/db_backups:/db_backups

  redis:
    image: redis:3.2.6-alpine
    restart: unless-stopped
