version: '2'
services:

  database:
    extends:
      file: common.yml
      service: database

  nzedb:
    extends:
      file: common.yml
      service: nzedb
    links:
      - database
      - redis
    depends_on:
      - database
      - redis

  redis:
    extends:
      file: common.yml
      service: redis
    
